services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234567890
      POSTGRES_DB: test-database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  config-server:
    build:
      context: ./config-server
    image: config-server
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-task:
    build:
      context: ./ms-task
    image: ms-task
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test

  ms-email:
    build:
      context: ./ms-email
    image: ms-email
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test

volumes:
  postgres-data:
