spring:
  application:
    name: ms-email
  config:
    import: "configserver:http://config-server:8888"
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
server:
  port: 8081