spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/prod-database
    username: postgres
    password: Postgres1234567890
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: prod@gmail.com
    password: prodpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

send:
  from: prod@gmail.com

max:
  retries: 5
