spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/prod-database
    username: postgres
    password: Postgres1234567890
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

max:
  task: 200
